development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: sample_db_app
  pool: 5
  username: vasistha
  password: vasistha
  host: localhost

test: &test
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: sample_db_app
  pool: 5
  username: vasistha
  password: vasistha
  host: localhost

cucumber:
  <<: *test
